# PORTAINER
- name: Create directory structure for portainer
  # Manage files and file properties
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: "{{ config_dir }}/docker/portainer"
    state: directory
    mode: 0755

- name: Copy portainer/docker-compose.yaml
  # Copy files to remote locations
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  ansible.builtin.copy:
    src: docker-compose-portainer.yaml
    dest: "{{ config_dir }}/docker/portainer/docker-compose.yaml"
    mode: "0640"

- name: Run docker-compose with portainer
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/portainer/"
    build: false
  become: false
  when: portainer_enable

- name: Stop docker-compose with portainer
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/portainer/"
    state: absent
  become: false
  when: portainer_enable == false
