# WIREGUARD
- name: Create directory structure for WireGuard
  # Manage files and file properties
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: "{{ config_dir }}/docker/wireguard"
    state: directory
    mode: 0755

- name: Copy docker-compose-wireguard.yaml
  # Template a file out to a target host
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
  ansible.builtin.template:
    src: docker-compose-wireguard.yaml
    dest: "{{ config_dir }}/docker/wireguard/docker-compose.yaml"
    mode: '0640'

- name: Run docker-compose with wireguard
  # Execute commands on targets
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  ansible.builtin.command: "{{ config_dir }}/.local/bin/docker-compose up -d"
  args:
    chdir: "{{ config_dir }}/docker/wireguard/"
  when: wireguard_enable

- name: Stop docker-compose with wireguard
  # Execute commands on targets
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  ansible.builtin.command: "{{ config_dir }}/.local/bin/docker-compose down"
  args:
    chdir: "{{ config_dir }}/docker/wireguard/"
  when: wireguard_enable == false
