# PIHOLE
- name: Install nslookup
  become: true
  # Manages apt-packages
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
  ansible.builtin.apt:
    name: dnsutils
    state: present

- name: Create directory structure for pihole
  # Manage files and file properties
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: "{{ config_dir }}/docker/pihole"
    state: directory
    mode: 0755

- name: Copy docker-compose-pihole.yaml
  # Template a file out to a target host
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
  ansible.builtin.template:
    src: docker-compose-pihole.yaml
    dest: "{{ config_dir }}/docker/pihole/docker-compose.yaml"
    mode: "0640"

- name: Ensure pihole is running
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/pihole/"
    build: false
  become: false
  when: pihole_enable

- name: Ensure pihole is not running
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/pihole/"
    state: absent
  become: false
  when: pihole_enable == false
