# My home automation setup:
# Node-Red + zigbee2mqtt + eclipse-mosquitto
- name: Create directory structure for Home-automation
  # Manage files and file properties
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "{{ config_dir }}/docker/homeautomation"
    - "{{ config_dir }}/docker/homeautomation/zigbee2mqtt--app-data"
    - "{{ config_dir }}/docker/homeautomation/nodered--data"
    - "{{ config_dir }}/docker/homeautomation/mqtt--mosquitto"

- name: Copy docker-compose-home-automation.yaml (as Template)
  # Template a file out to a target host
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
  ansible.builtin.template:
    src: docker-compose-home-automation.yaml
    dest: "{{ config_dir }}/docker/homeautomation/docker-compose.yaml"
    mode: "0640"

- name: Copy zigbee2mqtt--configuration.yaml
  # Copy files to remote locations
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
  ansible.builtin.copy:
    src: templates/zigbee2mqtt--configuration.yaml
    dest: "{{ config_dir }}/docker/homeautomation/zigbee2mqtt--app-data/configuration.yaml"
    # do NOT replace, if file already exist
    force: no
    mode: "0666"

- name: Ensure home-automation is running (IF homeautomation_enable == true)
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/homeautomation/"
    build: false
  become: false
  when: homeautomation_enable

- name: Ensure home-automation is not running (IF homeautomation_enable == false)
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/homeautomation/"
    state: absent
  become: false
  when: homeautomation_enable == false
