# START: My private GitHub SHMU scraper project -----
# Generate ssh keypair
- name: Ensure deploy key is present
  # Generate OpenSSH private and public keys
  # https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: ed25519
  register: ssh_key

# If a new deploy key is generated, authorize it in the GitHub shmu-scraper repo.
# You need to register GITHUB_TOKEN env variable with GitHub's "Personal access token"
# with "admin:public_key" and "repo" scopes. See: https://github.com/settings/tokens
- name: Ensure deploy key is authorized
  # Manages deploy keys for GitHub repositories
  # https://docs.ansible.com/ansible/latest/collections/community/general/github_deploy_key_module.html
  community.general.github_deploy_key:
    key: "{{ ssh_key.public_key }}"
    name: Raspberry Pi4
    state: present
    owner: dhlavaty
    repo: shmu-scraper
    token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

- name: Clone my private SHMU scraper GitHub repo
  # Deploy software (or files) from git checkouts
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
  ansible.builtin.git:
    repo: git@github.com:dhlavaty/shmu-scraper.git
    dest: /home/pi/docker/shmu-scraper/
    clone: true
    update: true
    key_file: ~/.ssh/id_rsa
    accept_hostkey: true

- name: Schedule a cron job to run my script periodically. Creates an entry like "1 21 * * * cd /home/pi/docker/shmu-scraper && ./run-in-docker.sh > /dev/null"
  ansible.builtin.cron:
    name: "run shmu-scraper"
    minute: "1"
    hour: "21"
    job: "cd /home/pi/docker/shmu-scraper && ./run-in-docker.sh > /dev/null"
# END: My private GitHub SHMU scraper project -----
