# START: My private GitHub SHMU scraper project -----
# Generate ssh keypair
- name: Ensure deploy key is present
  # Generate OpenSSH private and public keys
  # https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: ed25519
  register: ssh_key

# If a new deploy key is generated, authorize it in the GitHub shmu-scraper repo.
# You need to register GITHUB_TOKEN env variable with GitHub's "Personal access token"
# with "admin:public_key" and "repo" scopes. See: https://github.com/settings/tokens
- name: Ensure deploy key is authorized
  # Manages deploy keys for GitHub repositories
  # https://docs.ansible.com/ansible/latest/collections/community/general/github_deploy_key_module.html
  community.general.github_deploy_key:
    key: "{{ ssh_key.public_key }}"
    name: Raspberry Pi4
    state: present
    owner: dhlavaty
    repo: shmu-scraper
    token: "{{ shmu_scraper_github_token }}"

- name: Clone my private SHMU scraper GitHub repo
  # Deploy software (or files) from git checkouts
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
  ansible.builtin.git:
    repo: git@github.com:dhlavaty/shmu-scraper.git
    dest: "{{ config_dir }}/docker/shmu-scraper/"
    clone: true
    update: true
    key_file: ~/.ssh/id_rsa
    accept_hostkey: true

- name: Gathering users homedir ("echo {{ config_dir }}")
  # Execute commands on targets
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
  ansible.builtin.command: "echo {{ config_dir }}"
  register: homedir

- name: Users homedir
  # Print statements during execution
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
  ansible.builtin.debug:
    msg: homedir="{{ homedir.stdout }}"

- name: Schedule a cron job to run my script periodically. Creates an entry like "1 21 * * * cd {{ homedir.stdout }}/docker/shmu-scraper && ./run-in-docker.sh > /dev/null"
  # Manage cron.d and crontab entries
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html
  ansible.builtin.cron:
    name: "run shmu-scraper"
    minute: "1"
    hour: "21"
    job: "cd {{ homedir.stdout }}/docker/shmu-scraper && ./run-in-docker.sh > /dev/null"
