# WIREGUARD
- name: Create directory structure for WireGuard
  # Manage files and file properties
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
  ansible.builtin.file:
    path: "{{ config_dir }}/docker/wireguard"
    state: directory
    mode: 0755

- name: Copy docker-compose-wireguard.yaml
  # Template a file out to a target host
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
  ansible.builtin.template:
    src: docker-compose-wireguard.yaml
    dest: "{{ config_dir }}/docker/wireguard/docker-compose.yaml"
    mode: "0640"

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Wireguard is running
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/wireguard/"
    build: false
  become: false
  when: wireguard_enable

- name: Ensure Wireguard is not running
  # Manage multi-container Docker applications with Docker Compose
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker/wireguard/"
    state: absent
  become: false
  when: wireguard_enable == false
